services:
  sigpim-frontend:
    build: .
    container_name: sigpim-frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://sigpim-backend:8080

networks:
  default:
    name: sigpim_default
    external: true